events {
    worker_connections 1024;
}

http {
    client_max_body_size 100M;
    proxy_read_timeout    120s;
    proxy_connect_timeout 10s;

    # ── HumHub: porta 80 ────────────────────────────────────────────────────
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass         http://humhub:80;
            proxy_http_version 1.1;
            proxy_set_header   Host              $http_host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_set_header   Upgrade           $http_upgrade;
            proxy_set_header   Connection        "upgrade";
        }
    }

    # ── GLPI: porta 8080 ────────────────────────────────────────────────────
    server {
        listen 8080;
        server_name _;

        location / {
            proxy_pass         http://glpi:80;
            proxy_http_version 1.1;
            proxy_set_header   Host              $http_host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
